# Generated by Django 4.0.5 on 2022-06-13 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CheckFields',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(choices=[('1', 'English'), ('2', 'Urdu'), ('3', 'Punjabi'), ('4', 'German')], default='Select Language', max_length=1)),
            ],
        ),
    ]
