# Generated by Django 4.0.5 on 2022-06-13 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkmodel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkfields',
            name='choice',
            field=models.CharField(choices=[('1', 'English'), ('2', 'Urdu'), ('3', 'Punjabi'), ('4', 'German')], default='Select Language', max_length=50),
        ),
    ]
