# Generated by Django 4.0.5 on 2022-06-14 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='name',
            new_name='teacher_name',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='subject',
            new_name='teacher_subject',
        ),
        migrations.AddField(
            model_name='teacher',
            name='teacher_pic',
            field=models.FileField(max_length=250, null=True, upload_to='teacher_img/'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='teacher_qualification',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
