# Generated by Django 4.0.5 on 2022-06-13 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses_card', '0003_courses_course_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='course_type',
            field=models.CharField(choices=[('1', 'Data Scince'), ('2', 'AI and Machine Learning '), ('3', 'Web Development'), ('4', 'Data Analyst'), ('5', 'Mobile Development'), ('6', 'UI/UX Design'), ('7', 'Content Writing'), ('8', 'Self-Development')], default='UnSelected', max_length=1),
        ),
    ]
