# Generated by Django 4.0.5 on 2022-06-13 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses_card', '0004_alter_courses_course_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddCourseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_category', models.CharField(max_length=50)),
                ('course_code', models.CharField(max_length=50)),
            ],
        ),
    ]
