# Generated by Django 4.0.5 on 2022-06-13 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses_card', '0005_addcoursecategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addcoursecategory',
            name='course_code',
        ),
        migrations.AddField(
            model_name='addcoursecategory',
            name='course_category_code',
            field=models.CharField(default=569474, max_length=50),
        ),
    ]
