# Generated by Django 4.0.5 on 2022-06-13 18:34

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses_card', '0008_alter_addcoursecategory_course_category_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='addcoursecategory',
            name='category_img',
            field=models.FileField(default=None, max_length=250, null=True, upload_to='catagory_img/'),
        ),
        migrations.AddField(
            model_name='addcoursecategory',
            name='category_url',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='course_category', unique=True),
        ),
        migrations.AddField(
            model_name='courses',
            name='course_img',
            field=models.FileField(default=None, max_length=250, null=True, upload_to='course_img/'),
        ),
        migrations.AddField(
            model_name='courses',
            name='course_url',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='course_name', unique=True),
        ),
        migrations.AlterField(
            model_name='addcoursecategory',
            name='course_category_code',
            field=models.CharField(default=294944, max_length=50),
        ),
        migrations.AlterField(
            model_name='courses',
            name='course_type',
            field=models.CharField(choices=[], default='UnSelected', max_length=50),
        ),
    ]
