# Generated by Django 4.0.5 on 2022-06-14 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses_card', '0009_addcoursecategory_category_img_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addcoursecategory',
            name='course_category_code',
            field=models.CharField(default=61863, max_length=50),
        ),
        migrations.AlterField(
            model_name='courses',
            name='course_type',
            field=models.CharField(choices=[('1', 'Data Science'), ('2', 'Web Development'), ('3', 'Data Analyst'), ('4', 'Mobile Development'), ('5', 'UI/UX Design'), ('6', 'Content Writing'), ('7', 'Self-Development'), ('8', 'Languages'), ('9', 'IT'), ('10', 'Deep Learning')], default='UnSelected', max_length=50),
        ),
    ]
